# Generated by Django 3.2.9 on 2021-12-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211221_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
